language: bash

env:
  - APL_VERSION=1.6
  - APL_VERSION=1.7

before_install:
  - sudo bin/install-apl
  - cp -rv .travis/.gnu-apl ~
  - bin/fetch-configlet

script:
  - bin/configlet lint .
  - bin/run-all-tests
