services:
  - docker

language: bash

env:
  - APL_VERSION=1.6
  - APL_VERSION=1.7

before_install:
  - source .travis/installer
  - fetch_apl
  - docker build . -t apl --build-arg apl_version=${APL_VERSION}

script:
  - docker run apl 'bin/configlet lint .'
  - docker run apl 'bin/run-all-tests'
