services:
  - docker

language: bash

env:
  - APL_VERSION=1.6
  - APL_VERSION=1.7

before_install:
  - export APL_DEB=apl_${APL_VERSION}-1_amd64.deb
  - wget ftp://ftp.gnu.org/gnu/apl/${APL_DEB}
  - docker build . -t apl --build-arg apl_deb=${APL_DEB}
  - bin/fetch-configlet

script:
  - bin/configlet lint .
  - docker run apl 'bin/run-all-tests'
