language: bash

before_install:
  - wget ftp://ftp.gnu.org/gnu/apl/apl_1.7-1_amd64.deb
  - sudo dpkg -i apl_1.7-1_amd64.deb

script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - ./run-all-tests
